name: Go
on:
- push
- pull_request
jobs:
  build:
    name: CI Job
    strategy:
      matrix:
        os:
        - macos-10.15
        - ubuntu-18.04
        - windows-2019
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build
      run: make build
    - name: Test
      run: make lint test test-integration
