name: Testing

on:
- push
- pull_request

jobs:
  build:
    name: CI Job
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - name: Build
      run: make build
    - name: Test
      run: make lint test test-integration
